name: SEO Bot

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Reposyu çek
        uses: actions/checkout@v3

      - name: Node.js kur
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Playwright + Bot'u çalıştır
        run: |
          npm install
          npx playwright install --with-deps
          node index.js
