name: SEO Bot

on:
  schedule:
    - cron: "*/5 * * * *"  # Her 15 dakikada bir çalışır
  workflow_dispatch:

jobs:
  seo-bot-job:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Node.js ortamını kur
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Bağımlılıkları yükle
        run: npm install

      - name: SEO botu çalıştır
        run: node index.js
